---
- name: ensure Nextcloud prerequisites are installed
  package:
    name: "{{ dubzland_nextcloud_prerequisites }}"
    state: present
    install_recommends: no

- name: ensure the Nextcloud data directory exists
  file:
    path: "{{ dubzland_nextcloud_data_dir }}"
    state: directory
    owner: "{{ dubzland_nextcloud_web_user }}"
    group: "{{ dubzland_nextcloud_web_group }}"
    mode: 0750

- name: ensure the Nextcloud root directory exists
  file:
    path: "{{ dubzland_nextcloud_root }}"
    state: directory
    owner: "{{ dubzland_nextcloud_web_user }}"
    group: "{{ dubzland_nextcloud_web_group }}"
    mode: 0750

- name: ensure the Nextcloud archive is unpacked
  unarchive:
    src: "{{ dubzland_nextcloud_download_url }}"
    dest: "{{ dubzland_nextcloud_root }}"
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
    owner: "{{ dubzland_nextcloud_web_user }}"
    group: "{{ dubzland_nextcloud_web_group }}"
    creates: "{{ dubzland_nextcloud_root }}/config/config.sample.php"
