---
- name: Converge
  hosts: all
  tasks:
    - name: Override the version for Debian Stretch
      set_fact:
        dubzland_nextcloud_version: 15.0.14
      when: ansible_distribution_release == "stretch"
    - name: "Include ansible-role-nextcloud"
      include_role:
        name: "ansible-role-nextcloud"
