---
- name: Converge
  hosts: all
  tasks:
    - name: Override the version for Debian Stretch
      set_fact:
        dubzland_nextcloud_version: 15.0.14
      when: ansible_distribution_release == "stretch"
    - name: "Include ansible-role-nextcloud"
      include_role:
        name: "ansible-role-nextcloud"
      vars:
        dubzland_nextcloud_settings:
          - name: filelocking.enabled
            value: True
          - name: memcache.local
            value: "\\OC\\Memcache\\APCu"
          - name: memcache.distributed
            value: '\OC\Memcache\Redis'
          - name: redis
            value:
              host: "localhost"
              port: 6379
              timeout: "0.0"
        dubzland_nextcloud_apps:
          - name: maps
            state: present
            settings:
              - name: homepage
                state: absent
                value: 'http://www.google.com'
