---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-nextcloud"
      include_role:
        name: "ansible-role-nextcloud"
      vars:
        dubzland_nextcloud_settings:
          - name: filelocking.enabled
            value: 'true'
          - name: memcache.local
            value: "\\OC\\Memcache\\APCu"
        dubzland_nextcloud_apps:
          - name: maps
            state: present
            settings:
              - name: homepage
                state: absent
                value: 'http://www.google.com'
