---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: dubzland-nextcloud-debian9
    image: jdubz/docker-ci-debian:stretch-slim
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /var/cache/apt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: dubzland-nextcloud-debian10
    image: jdubz/docker-ci-debian:buster-slim
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/cache/apt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: dubzland-nextcloud-ubuntu16.04
    image: jdubz/docker-ci-ubuntu:xenial
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/cache/apt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: dubzland-nextcloud-ubuntu18.04
    image: jdubz/docker-ci-ubuntu:bionic
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/cache/apt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: dubzland-nextcloud-ubuntu19.10
    image: jdubz/docker-ci-ubuntu:eoan
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /var/cache/apt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: dubzland-nextcloud-ubuntu20.04
    image: jdubz/docker-ci-ubuntu:focal
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/cache/apt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: dubzland-nextcloud-ubuntu20.10
    image: jdubz/docker-ci-ubuntu:groovy
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/cache/apt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
