---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: dubzland-nextcloud-debian9
    image: jdubz/docker-ansible-debian9:latest
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: dubzland-nextcloud-debian10
    image: jdubz/docker-ansible-debian10:latest
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
provisioner:
  name: ansible
  config_options:
    default:
      stdout_callback: debug
  env:
    ANSIBLE_KEEP_REMOTE_FILES: 1
verifier:
  name: ansible
